In [ ]:
# Soru 1 – Liste Metotları
# Bir sınıfta öğrencilerin notları şu şekilde tutuluyor:
# notlar = [85, 92, 76, 92, 100, 76, 85, 92]
# • Listedeki tekrar eden notları silip benzersiz bir liste oluşturun.
# • En yüksek ve en düşük notu bulun.
# • Notları küçükten büyüğe sıralayın.

notlar = [85, 92, 76, 92, 100, 76, 85, 92]

def liste (input_list):
    unique_list = list(set(input_list))
    unique_list.sort()
    print("En yüksek not:", unique_list[-1])
    print("En düşük not:", unique_list[0])
    return unique_list

print(liste(notlar))


En yüksek not: 100
En düşük not: 76
[76, 85, 92, 100]


In [ ]:
# Soru 2 – Sayılar
# Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın.
# Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar.
# 153
sayı = int(input("Sayıyı giriniz: "))

def armstrong (sayı):
  basamak=len(str(sayı))
  toplam=0
  for i in range(basamak):
    toplam+=int(str(sayı)[i])**basamak
  if toplam==sayı:
    print("Armstrong sayısıdır.")
  else:
    print("Armstrong sayısı değildir.")

armstrong(sayı)



Sayıyı giriniz: 253
Armstrong sayısı değildir.


In [ ]:
# Soru 3 – Kümeler
# Aşağıdaki iki küme verilmiştir:
# A = {"Python", "R", "SQL", "Java"}
# B = {"C++", "Python", "JavaScript", "SQL"}
# • Ortak dilleri bulun.
# • Sadece A’da olan dilleri listeleyin.
# • İki kümenin birleşimini alfabetik olarak yazdırın.

A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

def listeler(input_dictiniory1,input_dictiniory2):
  print("Ortak diller:", input_dictiniory1.intersection(input_dictiniory2))
  print("Sadece A'da olan diller:", input_dictiniory1.difference(input_dictiniory2))
  print("Sadece B'de olan diller:", input_dictiniory2.difference(input_dictiniory1))
  print("İki kümenin birleşimleri:", input_dictiniory1.union(input_dictiniory2))

listeler(A,B)

Ortak diller: {'SQL', 'Python'}
Sadece A'da olan diller: {'R', 'Java'}
Sadece B'de olan diller: {'C++', 'JavaScript'}
İki kümenin birleşimleri: {'C++', 'Java', 'R', 'SQL', 'Python', 'JavaScript'}


In [ ]:
# Soru 4 – Modüller
# • random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin.
# • Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.

import random

rastgele_sayılar = [random.randint(1, 100) for _ in range(10)]
print(rastgele_sayılar)

import statistics

ortalama = statistics.mean(rastgele_sayılar)
standart_sapma = statistics.stdev(rastgele_sayılar)

print("Ortalama:", ortalama)
print("Standart Sapma:", standart_sapma)

[48, 77, 69, 17, 27, 41, 66, 26, 47, 93]
Ortalama: 51.1
Standart Sapma: 24.655177504487323


In [ ]:
# Soru 5 – Fonksiyonlar
# kelime_sayacı(metin) adında bir fonksiyon yazın.
# Fonksiyon verilen metindeki:
# • toplam kelime sayısını
# • en uzun kelimeyi
# • en sık geçen kelimeyi döndürsün.




metin = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."


def kelime_sayacı(metin):
    kelimeler = metin.split()
    toplam_kelime_sayısı = len(kelimeler)
    print("Toplam kelime sayısı:", toplam_kelime_sayısı)

    en_uzun_kelime = max(kelimeler, key=len)
    print("En uzun kelime:", en_uzun_kelime)

    kelime_frekansı = {}
    for kelime in kelimeler:
        if kelime in kelime_frekansı:
            kelime_frekansı[kelime] += 1
        else:
            kelime_frekansı[kelime] = 1
    en_cok_geçen_kelime = max(kelime_frekansı, key=kelime_frekansı.get)
    print("En sık geçen kelime:", en_cok_geçen_kelime)

kelime_sayacı(metin)


Toplam kelime sayısı: 69
En uzun kelime: reprehenderit
En sık geçen kelime: in


In [ ]:
# Soru 6 – Gömülü Fonksiyonlar
# Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:
# sayilar = [5, 12, 7, 18, 24, 3, 16]
# • Sadece çift sayıları filtreleyin.
# • Bu sayıların karelerini bulun.
# • Karelerini azalan sırada sıralayın.

sayilar = [5, 12, 7, 18, 24, 3, 16]

cift_sayılar=list(filter(lambda x: x % 2 == 0, sayilar))
print(cift_sayılar)

kareler=list(map(lambda x: x**2, cift_sayılar))
print(kareler)

kareler.sort(reverse=True)
print(kareler)

[12, 18, 24, 16]
[144, 324, 576, 256]
[576, 324, 256, 144]


In [ ]:
# Soru 7 – Lambda İfadeleri
# Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın.
# kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
# Bunu sorted + lambda ile yapın.

kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

kelime_uzunluk=sorted(kelimeler, key=lambda x: len(x))
print(kelime_uzunluk)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [ ]:
# Soru 8 – Metodlar
# Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon
# yazın.
# Örn: "abc12def3" → 12 + 3 = 15

import re

metin="hjujkıklo52ko9gfyfgcxfr7gyufyf8956huhıhjjohf14"

# Find all sequences of one or more digits
sayilar = [int(s) for s in re.findall(r'\d+', metin)]
print(sayilar)
print(sum(sayilar))

[52, 9, 7, 8956, 14]
9038


In [ ]:
# Soru 9 – (Ekstra) Numpy 1
# 10 elemanlı bir numpy dizisi oluşturun.
# • Elemanlar 0–50 arasında rastgele sayılar olsun.
# • Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun.


from array import array
import numpy as np

# Create a 10-element numpy array with random integers between 0 and 50
dizi = np.random.randint(0, 51, 10)
print("Numpy dizisi:", dizi)

# Calculate the mean, standard deviation, and maximum value
ortalama = np.mean(dizi)
standart_sapma = np.std(dizi)
en_buyuk_deger = np.max(dizi)

print("Ortalama:", ortalama)
print("Standart Sapma:", standart_sapma)
print("En Büyük Değer:", en_buyuk_deger)

Numpy dizisi: [13 33 41 20  1 23  4 18 21 15]
Ortalama: 18.9
Standart Sapma: 11.414464507807628
En Büyük Değer: 41


In [ ]:
# Soru 10 – (Ekstra) Numpy 2
# 5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin.
# • Her sütunun ortalamasını bulun.
# • 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun.


import numpy as np

# Create a 5x5 matrix with random values between 0 and 1
matris = np.random.rand(5, 5)
print("Rastgele Matris:")
print(matris)

ortalamalar = np.mean(matris, axis=0)
print("Her Sütunun Ortalaması:")
print(ortalamalar)

binary_matris = np.where(matris > 0.5, 1, 0)
print("Binary Matris:")
print(binary_matris)



Rastgele Matris:
[[0.80696429 0.37662358 0.6670982  0.81208442 0.47850417]
 [0.63806201 0.07243193 0.43763979 0.89071259 0.31519911]
 [0.18637891 0.25694136 0.95874356 0.548695   0.95526475]
 [0.56378848 0.85336867 0.70322665 0.77805047 0.17894649]
 [0.87974156 0.70523676 0.05357106 0.14358361 0.62510582]]
Her Sütunun Ortalaması:
[0.61498705 0.45292046 0.56405585 0.63462522 0.51060407]
Binary Matris:
[[1 0 1 1 0]
 [1 0 0 1 0]
 [0 0 1 1 1]
 [1 1 1 1 0]
 [1 1 0 0 1]]


In [ ]:
# Proje – “Kitap Satış Analiz Sistemi”
# Bir yayınevinin farklı türlerde ve yazarlarda kitapları var. Örnek veri:
kitaplar = [
 {"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
 {"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil":2020},
 {"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
 {"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
 {"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
 {"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500,"yil": 2021},
 {"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}]

In [ ]:
# 1. Fonksiyon Yazma:
#o en_cok_satan(kitaplar) → En çok satan kitabın bilgilerini döndürsün.
#o yazar_satislari(kitaplar) → Her yazarın toplam satışını bir sözlük olarak
#döndürsün.

def en_cok_satan(kitaplar):
  en_cok_satan_kitap = max(kitaplar, key=lambda x: x["satis"])
  return en_cok_satan_kitap


def yazar_satislari(kitaplar):
  yazar_satislari_dict = {}
  for kitap in kitaplar:
    yazar = kitap["yazar"]
    satis = kitap["satis"]
    if yazar in yazar_satislari_dict:
      yazar_satislari_dict[yazar] += satis
    else:
      yazar_satislari_dict[yazar] = satis
  return yazar_satislari_dict

print("En çok satan kitap:", en_cok_satan(kitaplar))
print("Yazar satışları:", yazar_satislari(kitaplar))

En çok satan kitap: {'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}
Yazar satışları: {'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}


In [ ]:
# 2. Liste ve Küme İşlemleri:
# o Tüm kitap türlerini (tur) küme halinde çıkarın (tekrar eden türler olmadan).
# o Satış adedi 1000’den fazla olan kitapların isimlerini bir listede toplayın.

def kitap_tur(kitaplar):
  turler=set()
  for kitap in kitaplar:
    turler.add(kitap["tur"])
  print("Tüm kitap türleri:", turler)

  kitap_isimleri_bin_ustu = []
  for kitap in kitaplar:
    if kitap["satis"] > 1000:
      kitap_isimleri_bin_ustu.append(kitap["isim"])
      print(f"Kitap Adı: {kitap['isim']}, Satış Adedi: {kitap['satis']}") # Corrected print statement

  print("Satış adedi 1000'den fazla olan kitap isimleri:", kitap_isimleri_bin_ustu)


kitap_tur(kitaplar)

Tüm kitap türleri: {'Sanat', 'Sosyal', 'Bilim', 'Akademik'}
Kitap Adı: Veri Bilimi 101, Satış Adedi: 1200
Kitap Adı: Makine Öğrenmesi, Satış Adedi: 1800
Kitap Adı: Matematiksel Modelleme, Satış Adedi: 1500
Satış adedi 1000'den fazla olan kitap isimleri: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']


In [9]:
# 3. Lambda / Filter / Map Kullanımı:
# o filter ile 2020’den sonra çıkan kitapları süzün.
# o map ile tüm satış adetlerini %10 artırılmış şekilde yeni bir listeye aktarın.
# o sorted + lambda ile kitapları satış miktarına göre azalan şekilde sıralayın.

kitaplar_2020_sonrası = list(filter(lambda x: x["yil"] >= 2020, kitaplar))
artirilmis_satislar = list(map(lambda x: x["satis"] * 1.1, kitaplar))
kitaplar_satista_sirali = sorted(kitaplar, key=lambda x: x["satis"], reverse=True)
print("2020'den Sonra Çıkan Kitaplar:", kitaplar_2020_sonrası)
print("Artırılmış Satışlar:", artirilmis_satislar)
print("Sıralanmış Kitaplar (Satista Sirali):", kitaplar_satista_sirali)


2020'den Sonra Çıkan Kitaplar: [{'isim': 'Veri Bilimi 101', 'yazar': 'Ali', 'tur': 'Bilim', 'satis': 1200, 'yil': 2021}, {'isim': 'Python ile Yapay Zeka', 'yazar': 'Ayşe', 'tur': 'Bilim', 'satis': 950, 'yil': 2020}, {'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}, {'isim': 'Matematiksel Modelleme', 'yazar': 'Ali', 'tur': 'Akademik', 'satis': 1500, 'yil': 2021}, {'isim': 'Bilgi Toplumu', 'yazar': 'Ayşe', 'tur': 'Sosyal', 'satis': 600, 'yil': 2022}]
Artırılmış Satışlar: [1320.0, 1045.0, 770.0000000000001, 1980.0000000000002, 440.00000000000006, 1650.0000000000002, 660.0]
Sıralanmış Kitaplar (Satista Sirali): [{'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}, {'isim': 'Matematiksel Modelleme', 'yazar': 'Ali', 'tur': 'Akademik', 'satis': 1500, 'yil': 2021}, {'isim': 'Veri Bilimi 101', 'yazar': 'Ali', 'tur': 'Bilim', 'satis': 1200, 'yil': 2021}, {'isim': 'Python ile Yapay Zeka', 'yazar': 'Ayşe', 'tur': 'Bilim',

In [5]:
# 4. İstatistiksel Analiz:
# o Ortalama satış adedini bulun.
# o En çok satış yapan türü bulun.
# o Satışların standart sapmasını hesaplamak için statistics modülünü kullanın

import statistics

ortalama_satis = statistics.mean([kitap["satis"] for kitap in kitaplar])
en_cok_satan_tur= max(set([kitap["tur"] for kitap in kitaplar]), key=lambda tur: sum([kitap["satis"] for kitap in kitaplar if kitap["tur"] == tur]))
satis_sapmasi=statistics.stdev([kitap["satis"] for kitap in kitaplar])
print("Ortalama Satış Adedi:", ortalama_satis)
print("En Çok Satan Tür:", en_cok_satan_tur)
print("Satışların Standart Sapması:", satis_sapmasi)

Ortalama Satış Adedi: 1021.4285714285714
En Çok Satan Tür: Bilim
Satışların Standart Sapması: 506.5053001179939


In [7]:
# 5. Ekstra (Zorlayıcı): Train/Test Simülasyonu
# o Kitap listesini rastgele %70 eğitim (train), %30 test verisine ayırın
# (random.sample).
# o Eğitim verisinden yazarların ortalama satışını hesaplayın.
# o Test verisinde, hangi kitapların satışlarının bu ortalamanın üzerinde olduğunu
# kontrol edin.

import random


# Kitap listesini rastgele %70 eğitim (train), %30 test verisine ayırın
train_size = int(len(kitaplar) * 0.7)
train_data = random.sample(kitaplar, train_size)
test_data = [kitap for kitap in kitaplar if kitap not in train_data]

print("Eğitim Verisi:")
print(train_data)
print("\nTest Verisi:")
print(test_data)

# Eğitim verisinden yazarların ortalama satışını hesaplayın.
yazar_satis_toplam = {}
yazar_kitap_sayisi = {}

for kitap in train_data:
    yazar = kitap["yazar"]
    satis = kitap["satis"]
    if yazar in yazar_satis_toplam:
        yazar_satis_toplam[yazar] += satis
        yazar_kitap_sayisi[yazar] += 1
    else:
        yazar_satis_toplam[yazar] = satis
        yazar_kitap_sayisi[yazar] = 1

yazar_ortalama_satis = {yazar: yazar_satis_toplam[yazar] / yazar_kitap_sayisi[yazar] for yazar in yazar_satis_toplam}

print("\nEğitim Verisinden Yazar Ortalama Satışları:")
print(yazar_ortalama_satis)

# Test verisinde, hangi kitapların satışlarının bu ortalamanın üzerinde olduğunu kontrol edin.
print("\nTest Verisindeki Kitapların Ortalama Üzerinde Satışları:")
for kitap in test_data:
    yazar = kitap["yazar"]
    satis = kitap["satis"]
    if yazar in yazar_ortalama_satis and satis > yazar_ortalama_satis[yazar]:
        print(f"{kitap['isim']} (Yazar: {yazar}): Satış ({satis}) ortalama ({yazar_ortalama_satis[yazar]:.2f}) üzerinde.")
    elif yazar in yazar_ortalama_satis:
         print(f"{kitap['isim']} (Yazar: {yazar}): Satış ({satis}) ortalama ({yazar_ortalama_satis[yazar]:.2f}) altında veya eşit.")
    else:
        print(f"{kitap['isim']} (Yazar: {yazar}): Eğitim verisinde yazar bilgisi bulunamadı.")



Eğitim Verisi:
[{'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}, {'isim': 'Bilgi Toplumu', 'yazar': 'Ayşe', 'tur': 'Sosyal', 'satis': 600, 'yil': 2022}, {'isim': 'Veri Görselleştirme', 'yazar': 'Deniz', 'tur': 'Sanat', 'satis': 400, 'yil': 2018}, {'isim': 'İstatistik Temelleri', 'yazar': 'Ali', 'tur': 'Akademik', 'satis': 700, 'yil': 2019}]

Test Verisi:
[{'isim': 'Veri Bilimi 101', 'yazar': 'Ali', 'tur': 'Bilim', 'satis': 1200, 'yil': 2021}, {'isim': 'Python ile Yapay Zeka', 'yazar': 'Ayşe', 'tur': 'Bilim', 'satis': 950, 'yil': 2020}, {'isim': 'Matematiksel Modelleme', 'yazar': 'Ali', 'tur': 'Akademik', 'satis': 1500, 'yil': 2021}]

Eğitim Verisinden Yazar Ortalama Satışları:
{'Can': 1800.0, 'Ayşe': 600.0, 'Deniz': 400.0, 'Ali': 700.0}

Test Verisindeki Kitapların Ortalama Üzerinde Satışları:
Veri Bilimi 101 (Yazar: Ali): Satış (1200) ortalama (700.00) üzerinde.
Python ile Yapay Zeka (Yazar: Ayşe): Satış (950) ortalama (600.00) üzerinde.
Matema