In [4]:
# 1. 1. Numpy ile Matris İşlemleri
# - 5x5 boyutunda rastgele (0-100 arasında) tam sayılardan oluşan bir matris oluşturun.
# - Bu matrisin:
 # • Ortalama, standart sapma ve varyansını hesaplayın.
 # • En büyük ve en küçük değerlerini bulun.
 # • Köşegenindeki elemanların toplamını bulun.

import numpy as np
import random as rn

matris = np.random.randint(0, 100, (5, 5))
print("Matris:")
print(matris)

# Calculate statistics
mean = np.mean(matris)
std_dev = np.std(matris)
variance = np.var(matris)
max_val = np.max(matris)
min_val = np.min(matris)
diagonal_sum = np.trace(matris)

print("\nİstatistikler:")
print(f"Ortalama: {mean}")
print(f"Standart Sapma: {std_dev}")
print(f"Varyans: {variance}")
print(f"En büyük değer: {max_val}")
print(f"En küçük değer: {min_val}")
print(f"Köşegen elemanları toplamı: {diagonal_sum}")

Matris:
[[90 69 10  3 81]
 [93 76 66  1 61]
 [21 13 61 55 12]
 [22 72 30 27 88]
 [54 62 39 40 19]]

İstatistikler:
Ortalama: 46.6
Standart Sapma: 28.655191501715706
Varyans: 821.12
En büyük değer: 93
En küçük değer: 1
Köşegen elemanları toplamı: 273


In [8]:
#2. 2. Numpy ile Veri Simülasyonu
#- 1000 adet öğrencinin sınav puanlarını (0-100 arası, normal dağılımdan gelen) simüle edin.
#- Ortalama, medyan ve standart sapmayı hesaplayın.
#- 50’den düşük alan kaç öğrenci olduğunu bulun.

ogrenci_puanlari = np.random.normal(50, 10, 1000)
ortalama_puan = np.mean(ogrenci_puanlari)
medyan_puan = np.median(ogrenci_puanlari)
standart_sapma = np.std(ogrenci_puanlari)
kalan_ogrenci=ogrenci_puanlari[ogrenci_puanlari<50]
print("Öğrenci puanları:")
print(ogrenci_puanlari)
print("\nİstatistikler:")
print(f"Ortalama: {ortalama_puan}")
print(f"Medyan: {medyan_puan}")
print(f"Standart Sapma: {standart_sapma}")
print(f"50'den düşük alan öğrenci sayısı: {len(kalan_ogrenci)}")


Öğrenci puanları:
[38.08962074 67.14265714 54.519035   69.79120937 66.89037335 45.54798233
 47.61963458 58.01768592 45.6982948  53.27285955 55.2635112  65.66110744
 51.85877671 53.04954713 57.87014663 50.13250036 33.33508186 59.78810954
 51.21026863 50.97122758 49.96132679 47.23369299 42.59146168 54.69657806
 34.81953035 42.57456202 48.24757418 47.5916727  44.41740676 48.54142013
 47.51344018 66.11694722 62.96311196 54.61658178 38.60925733 48.0808767
 62.0829682  52.76964756 39.4105495  58.18161062 52.09334996 56.10074509
 54.60874326 46.63570967 64.41688079 55.86370484 43.51810591 44.5011043
 58.97965593 54.19807544 67.13421933 43.65741547 57.39582654 55.92211825
 50.7643348  49.44574642 53.79459866 52.61705245 57.96447305 72.30003113
 68.50410488 65.30747827 50.41174421 54.21467086 41.50307817 45.1961662
 49.99771737 47.07283156 53.61070275 44.774621   56.13229276 46.63564261
 42.13762649 35.12234824 53.57196638 49.16110355 47.51188293 34.26656873
 36.20177083 65.30755567 53.84925651

In [11]:
#• Görevler:
#3. 1. Veri setini Pandas DataFrame olarak oluşturun.
#4. 2. Her ders için ortalama puanı bulun.
#5. 3. En yüksek matematik notunu alan öğrenciyi bulun.
#6. 4. Her öğrencinin not ortalamasını hesaplayan yeni bir sütun ekleyin.
#7. 5. Bölümlere göre gruplayarak her bölümün ortalama başarılarını hesaplayın.
#8. 6. Ortalaması 70’in üzerinde olan öğrencileri filtreleyin.
from google.colab import files
import pandas as pd

uploaded = files.upload()

# Assuming the uploaded file is a CSV, replace "your_dataset.csv" with the actual filename
# If it's a different format, use the appropriate pandas read function (e.g., pd.read_excel)
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

# Display the first few rows of the DataFrame to verify
print("DataFrame created from the dataset:")
display(df.head())

Saving ogrenci_bilgileri.csv to ogrenci_bilgileri (2).csv
DataFrame created from the dataset:


Öğrenci  Yaş       Bölüm  Matematik  Fizik  Kimya
0     Ali   20  Bilgisayar         70     65     80
1    Ayşe   21       Fizik         60     75     85
2  Mehmet   19       Kimya         80     70     65
3  Zeynep   22  Bilgisayar         90     85     95
4   Ahmet   20       Fizik         55     60     70

In [12]:
# 2. Her ders için ortalama puanı bulun.
average_scores = df[['Matematik', 'Fizik', 'Kimya']].mean()
print("\nHer ders için ortalama puanlar:")
print(average_scores)


Her ders için ortalama puanlar:
Matematik    76.625
Fizik        74.625
Kimya        81.500
dtype: float64


In [13]:
# 3. En yüksek matematik notunu alan öğrenciyi bulun.
highest_math_student = df.loc[df['Matematik'].idxmax()]
print("\nEn yüksek matematik notunu alan öğrenci:")
print(highest_math_student)


En yüksek matematik notunu alan öğrenci:
Öğrenci           Elif
Yaş                 23
Bölüm        Matematik
Matematik           95
Fizik               90
Kimya               85
Name: 5, dtype: object


In [14]:
#  4. Her öğrencinin not ortalamasını hesaplayan yeni bir sütun ekleyin.
df['Ortalama Not'] = df[['Matematik', 'Fizik', 'Kimya']].mean(axis=1)
print("\nDataFrame with student averages:")
display(df.head())


DataFrame with student averages:


Öğrenci  Yaş       Bölüm  Matematik  Fizik  Kimya  Ortalama Not
0     Ali   20  Bilgisayar         70     65     80     71.666667
1    Ayşe   21       Fizik         60     75     85     73.333333
2  Mehmet   19       Kimya         80     70     65     71.666667
3  Zeynep   22  Bilgisayar         90     85     95     90.000000
4   Ahmet   20       Fizik         55     60     70     61.666667

In [15]:
# 5. Bölümlere göre gruplayarak her bölümün ortalama başarılarını hesaplayın.
department_averages = df.groupby('Bölüm')['Ortalama Not'].mean()
print("\nBölümlere göre ortalama başarılar:")
print(department_averages)


Bölümlere göre ortalama başarılar:
Bölüm
Bilgisayar    83.222222
Fizik         67.500000
Kimya         73.000000
Matematik     90.000000
Name: Ortalama Not, dtype: float64


In [16]:
# 6. Ortalaması 70’in üzerinde olan öğrencileri filtreleyin.
students_above_70 = df[df['Ortalama Not'] > 70]
print("\nOrtalaması 70'in üzerinde olan öğrenciler:")
display(students_above_70)


Ortalaması 70'in üzerinde olan öğrenciler:


Öğrenci  Yaş       Bölüm  Matematik  Fizik  Kimya  Ortalama Not
0     Ali   20  Bilgisayar         70     65     80     71.666667
1    Ayşe   21       Fizik         60     75     85     73.333333
2  Mehmet   19       Kimya         80     70     65     71.666667
3  Zeynep   22  Bilgisayar         90     85     95     90.000000
5    Elif   23   Matematik         95     90     85     90.000000
6   Burak   21       Kimya         75     68     80     74.333333
7   Deniz   22  Bilgisayar         88     84     92     88.000000